/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import controladores.Controlador;
import modelo.Config;
import modelo.ModeloFacturas;
import java.awt.AWTException;
import java.awt.Color;
import java.awt.Image;
import java.awt.MenuItem;
import java.awt.PopupMenu;
import java.awt.SystemTray;
import java.awt.Toolkit;
import java.awt.TrayIcon;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JToggleButton;

/**
 *
 * @author juanseoane
 */
public class PanelControl extends javax.swing.JFrame {

    static Image icon;
    static TrayIcon trayIcon;
    static PopupMenu popMenu;
    
    private static boolean botonpulsado = false;
    private static int botonactivo = 1;
    public static PanelControl instancia = null;
    public static int modo;
    
    private PanelControl() {
        initComponents();
        startup();
        this.setTitle("Panel Control : "+Config.getConfig().getUsuario());
        this.lblTrimestre.setText(Config.getConfig().getAnho().getTrimestre()+"");
        this.lblAnho.setText(Config.getConfig().getAnho().getAnho()+"");
        this.lblEntradas.setText(ModeloFacturas.getNumeroFacturas()+"");
        this.toFront();
        this.setAlwaysOnTop(true);
        this.setAutoRequestFocus(false);
        this.modo = Controlador.NAV;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnFCT = new javax.swing.JButton();
        btnRS = new javax.swing.JButton();
        btnNTS = new javax.swing.JButton();
        btnCFG = new javax.swing.JButton();
        btnCJA = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblEntradas = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblTrimestre = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblAnho = new javax.swing.JLabel();
        btnautosave = new javax.swing.JButton();
        toggleModo = new javax.swing.JToggleButton();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Panel Control");
        setAlwaysOnTop(true);
        setIconImage(icon);
        setIconImages(startup());
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnFCT.setText("FCT");
        btnFCT.setToolTipText("<html>Entra en el MODO FACTURAS</html>");
        btnFCT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFCTActionPerformed(evt);
            }
        });

        btnRS.setText("R.S.");
        btnRS.setToolTipText("<html>Entra en el MODO DISTRIBUIDORES</html>");
        btnRS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRSActionPerformed(evt);
            }
        });

        btnNTS.setText("NTS");
        btnNTS.setToolTipText("<html>Abre la VENTANA DE NOTAS<br/>\nde las Facturas y los Distribuidores</html>");
        btnNTS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNTSActionPerformed(evt);
            }
        });

        btnCFG.setText("CFG");
        btnCFG.setToolTipText("<html>Abre la VENTANA DE CONFIGURACION<br/>\nEl programa se apaga al salir de ellla,<br/>\npara aplicar los cambios<br/>\nTendrá que volver a ejecutarlo para que<br/>\nestos cambios surtan efecto</html>");
        btnCFG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCFGActionPerformed(evt);
            }
        });

        btnCJA.setText("CAJA");
        btnCJA.setToolTipText("<html>Entra en el MODO CAJA</html>");
        btnCJA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCJAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnCFG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNTS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRS)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFCT)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCJA))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btnCJA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnFCT, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnRS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnNTS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btnCFG, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jLabel1.setText("entradas");

        lblEntradas.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblEntradas.setText("999");

        jLabel4.setText("trimestre");

        lblTrimestre.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblTrimestre.setText("1");
        lblTrimestre.setToolTipText("<html>Muestra el trimestre actual<br/>\n0 significa año completo (sin trimestres)<br/>\nPuede cambiarlo en la VENTANA DE CONFIGURACION</html>");

        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("AÑO");

        lblAnho.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lblAnho.setText("2013");
        lblAnho.setToolTipText("<html>Muestra el año actual<br/>\nPuede cambiarlo en la VENTANA DE CONFIGURACION</html>");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                    .addComponent(lblEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrimestre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAnho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEntradas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTrimestre)
                    .addComponent(lblAnho)))
        );

        btnautosave.setText("COPIA AUTO");
        btnautosave.setToolTipText("<html>Use este boton para generar una<br/>\nCOPIA DE SEGURIDAD AUTOMATICA<br/>\nde todos sus ficheros actuales<br/></html>");
        btnautosave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnautosaveActionPerformed(evt);
            }
        });

        toggleModo.setText("MODO NAV");
        toggleModo.setToolTipText("<html>Use este boton para cambiar<br/>\n entre el modo de NAVEGACION<br/> \npor los datos y el modo de<br/> \nINGRESO de facturas<html>");
        toggleModo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleModoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnautosave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(toggleModo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btnautosave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(toggleModo))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private List<Image> startup(){
        
        popMenu = new PopupMenu();
        MenuItem item1 = new MenuItem("Exit");
        popMenu.add(item1);
        
        icon = Toolkit.getDefaultToolkit().getImage("imagenes/tray.png");
        setIconImage(icon);
        List<Image> listaIconos = new ArrayList<Image>();
        listaIconos.add(icon);
        
        trayIcon = new TrayIcon(icon, "Facturas SIL v2.0", popMenu);

               
        if (SystemTray.isSupported()) {
          SystemTray tray = SystemTray.getSystemTray();

          trayIcon.setImageAutoSize(true);
          trayIcon.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
              trayIcon.displayMessage("Tester!", "Some action performed", TrayIcon.MessageType.INFO);
            }
          });

          try {
            tray.add(trayIcon);
          } catch (AWTException e) {
            System.out.println("TrayIcon could not be added.");
          }
        }else
          System.out.println("TrayIcon could not be added. SystemTray not supported");
        
        return listaIconos;
    }
    
    public static void setNumfacturas(int i){
        lblEntradas.setText(i +"");
    }
    public static void setAño(int i){
        lblAnho.setText(i+"");
    }
    public static void setTrimestre(int i){
        lblTrimestre.setText(i+"");
    }
    public void setUsuario(String user){
        this.setTitle("Panel Control : "+Config.getConfig().getUsuario());
    }
    
    public static int getModo(){
        return modo;
    }
    
    private void btnCFGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCFGActionPerformed
        botonactivo = 4;
        botonpulsado = true;
    }//GEN-LAST:event_btnCFGActionPerformed

    private void btnNTSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNTSActionPerformed
        botonactivo = 3;
        botonpulsado = true;

    }//GEN-LAST:event_btnNTSActionPerformed

    private void btnRSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRSActionPerformed
        botonactivo = 2;
        botonpulsado = true;

    }//GEN-LAST:event_btnRSActionPerformed

    private void btnFCTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFCTActionPerformed
        botonactivo = 1;
        botonpulsado = true;
    }//GEN-LAST:event_btnFCTActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void btnCJAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCJAActionPerformed
         botonactivo = 5;
        botonpulsado = true;
    }//GEN-LAST:event_btnCJAActionPerformed

    private void btnautosaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnautosaveActionPerformed
        botonactivo = 6;
        botonpulsado = true;
    }//GEN-LAST:event_btnautosaveActionPerformed

    private void toggleModoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleModoActionPerformed
        if (((JToggleButton)(evt.getSource())).isSelected()){
            toggleModo.setText("MODO INGR");
            toggleModo.setBackground(new Color(240,200,0));
            modo = Controlador.INGR;
        }
        else if (!((JToggleButton)(evt.getSource())).isSelected()){
            toggleModo.setText("MODO NAV");
            toggleModo.setBackground(new Color(240,240,240));
            modo = Controlador.NAV;
        }
        botonactivo = 7;
        botonpulsado = true;
    }//GEN-LAST:event_toggleModoActionPerformed
    
    public int seleccion(){
        return botonactivo;
    }
    public boolean botonpulsado(){
        return botonpulsado;
    }
    public static void pulsarboton(int boton){
        botonactivo = boton;
        botonpulsado = true;
    }
    public static void reset(){
        botonpulsado = false;
        PanelControl.getPanelControl().setAlwaysOnTop(true);
        PanelControl.getPanelControl().toFront();
        PanelControl.getPanelControl().repaint();
    }
    public static PanelControl getPanelControl(){
        if (instancia == null)
            instancia = new PanelControl();
         return instancia;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelControl().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCFG;
    private javax.swing.JButton btnCJA;
    private javax.swing.JButton btnFCT;
    private javax.swing.JButton btnNTS;
    private javax.swing.JButton btnRS;
    private javax.swing.JButton btnautosave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private static javax.swing.JLabel lblAnho;
    public static javax.swing.JLabel lblEntradas;
    private static javax.swing.JLabel lblTrimestre;
    private javax.swing.JToggleButton toggleModo;
    // End of variables declaration//GEN-END:variables
}
